name: Build iOS Mod
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: iOS
          
      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: ios-fps-mod
          path: ${{ steps.build.outputs.build-output }}

